### ISSUE TITLE
'flutter run' not working

### ISSUE THREAD

**Issue by lacucaracha** [audiooffler/JucyFluttering#1]
Hello Martin! 

Thank you for publishing this great project!!
I got a question. Building with xCode works just fine. Since it doesn't allows hot reloading (which is incredibly convenient in flutter) I tried, to run it via flutter run, which, unfortunately doesn't work. 

**Error:** 
`Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, getAppName): symbol not found)`

Do you have any suggestion on how I might wanna fix it?

Best,
Bernhard

Full Error Message:
` ════════ Exception caught by widgets library` `═══════════════════════════════════════════════════════`
`The following ArgumentError was thrown building MyApp(dirty):`
`Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, getAppName): symbol not found)`

`The relevant error-causing widget was: `
`  MyApp file:///Users/bernhardwendt/Downloads/JucyFluttering-master/fluttering/lib/main.dart:5:10`
`When the exception was thrown, this was the stack: `
`#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)`
`#1      juceGetAppNameUTF8 (package:fluttering/jucy_fluttering_interop.dart:71:10)`
`#2      juceGetAppNameUTF8 (package:fluttering/jucy_fluttering_interop.dart)`
`#3      getAppName (package:fluttering/jucy_fluttering_interop.dart:77:26)`
`#4      MyApp.build (package:fluttering/main.dart:13:14)`

**Comment by audiooffler** [comment]
Hi Bernhard,

have you tried the following for enabling hot reloading?

While running / debugging from xCode, one may call flutter attach from terminal (first go to cd ./fluttering).


Cheers
Martin
--
Dresden
Am 16. März 2021, 17:10 +0100 schrieb lacucaracha ***@***.***>:

**Comment by lacucaracha** [comment]
Thank you for your fast response!

`flutter attach` prints the following: 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/311725/111361177-dbbc6600-868d-11eb-8a5c-73286e873e14.png">

When I try any of these, terminal basically does nothing. It's not stuck but it sticks to to point where the command is entered. 

I also tried to attach with the device ID which gave me the same thing...
Any ideas?

**Comment by audiooffler** [comment]
Sorry, i currently have no test environment to give it a try and don‘t have and idea…
I hope you find out and would ne Interested in the solution…

Cheers,
Martin
Am 16. März 2021, 19:30 +0100 schrieb lacucaracha ***@***.***>:

**Comment by lacucaracha** [comment]
@audiooffler all my bad! i had two builds running, so `futter attach` didn't know which app to attach to. just as the Error Message said. I removed all build apps from the Simulator and built again. now it works like a charm.

thank you for your help!

Best,
Bernhard
